# Step 3.1: Apache Status Analysis

In [1]:
import pandas as pd 
import os

In [2]:
# Open Results
df = pd.read_csv('ApacheStatusCheckerResults.csv')

In the following table we can see, for each project:
- Original: commits where they detected a building system (Maven) and built successfully (Previous Experiment)
- Replicated: commits where they detected a system build (Maven) and we have built successfully (Current experiment)
- Real Replicated: commits where we have detected a build system (Maven) and have been able to build successfully (Current experiment).
- Our Replicated + Fixes: of commits where we have detected any system build (Ant/Maven) and were able to build successfully.
- Complete: # of commits we have been able to build successfully.
- Original Buildable commits: # of commits in which they detected a pom.xml
- Buildable commits: # of commits in which we detected a pom.xml
- TotalCommits: # of repository commits.

In [3]:
df

,Project,TotalCommits,Original Buildable commits,Original,Original (%),Replicated,Replicated (%),Real Buildable commits,Real Replicated,Real Replicated (%),Ant Fails,Ant Success,Real Buildable commits + Ant,Real Replicated + Ant,Real Replicated + Ant (%),Complete
0,isis,4817,2062,300,14.548982,90,4.364694,2062,90,4.364694,0,0,2062,90,4.364694,1.868383
1,james-hupa,686,677,96,14.180207,0,0.000000,677,0,0.000000,0,0,677,0,0.000000,0.000000
2,james-jdkim,124,123,9,7.317073,9,7.317073,123,9,7.317073,0,0,123,9,7.317073,7.258065
3,james-jsieve,527,393,140,29.598309,0,0.000000,393,0,0.000000,51,81,525,81,15.428571,15.370019
4,james-jspf,621,384,166,37.219731,166,43.229167,384,166,43.229167,0,62,446,228,51.121076,36.714976
5,james-mime4j,733,722,108,14.958449,70,9.695291,722,70,9.695291,0,0,722,70,9.695291,9.549795
6,james-postage,74,63,0,0.000000,0,0.000000,63,0,0.000000,8,0,71,0,0.000000,0.000000
7,jclouds,5074,1039,0,0.000000,0,0.000000,5072,94,1.853312,0,0,5072,94,1.853312,1.852582
8,jena,2680,2647,376,14.204760,329,12.429165,2647,329,12.429165,0,0,2647,329,12.429165,12.276119
9,kalumet,172,170,63,37.058824,5,2.941176,170,5,2.941176,0,0,170,5,2.941176,2.906977
10,karaf-cave,103,103,82,79.611650,31,30.097087,103,31,30.097087,0,0,103,31,30.097087,30.097087
11,karaf-cellar,460,460,25,5.434783,1,0.217391,460,1,0.217391,0,0,460,1,0.217391,0.217391
12,log4j-component,68,60,46,67.647059,46,76.666667,60,46,76.666667,0,8,68,54,79.411765,79.411765
13,log4j-extras,213,213,197,92.488263,197,92.488263,213,197,92.488263,0,0,213,197,92.488263,92.488263
14,log4j-receivers,96,96,0,0.000000,0,0.000000,96,0,0.000000,0,0,96,0,0.000000,0.000000
15,log4j-zeroconf,25,25,11,44.000000,11,44.000000,25,11,44.000000,0,0,25,11,44.000000,44.000000
16,mahout,3156,3117,726,23.291627,577,18.511389,3117,577,18.511389,4,31,3152,608,19.289340,19.264892
17,manifoldcf-integration-solr-4.x,3355,3,3,100.000000,3,100.000000,3,3,100.000000,1582,1766,3351,1769,52.790212,52.727273
18,maven,9427,9196,1694,18.421053,1704,18.529796,9196,1704,18.529796,0,0,9196,1704,18.529796,18.075740
19,maven-2,5636,5405,1150,21.276596,1120,20.721554,5405,1120,20.721554,0,0,5405,1120,20.721554,19.872250
20,maven-app-engine,54,54,38,70.370370,38,70.370370,54,38,70.370370,0,0,54,38,70.370370,70.370370
21,maven-doxia,1543,1541,184,11.940299,155,10.058404,1541,155,10.058404,0,0,1541,155,10.058404,10.045366
22,maven-doxia-tools,306,303,119,39.273927,119,39.273927,303,119,39.273927,0,0,303,119,39.273927,38.888889
23,maven-enforcer,411,408,177,43.382353,122,29.901961,408,122,29.901961,0,0,408,122,29.901961,29.683698
24,maven-integration-testing,2042,2037,380,18.654885,380,18.654885,2037,380,18.654885,0,0,2037,380,18.654885,18.609207
25,maven-jxr,232,227,209,92.070485,225,99.118943,227,225,99.118943,0,0,227,225,99.118943,96.982759
26,maven-plugins,11812,11221,21,0.187149,21,0.187149,11810,369,3.124471,0,0,11810,369,3.124471,3.123942
27,maven-plugin-testing,98,96,90,93.750000,90,93.750000,96,90,93.750000,0,0,96,90,93.750000,91.836735
28,maven-resources,149,147,90,61.224490,90,61.224490,147,90,61.224490,0,0,147,90,61.224490,60.402685
29,maven-scm,1789,1769,1293,73.092142,1292,73.035613,1769,1292,73.035613,0,0,1769,1292,73.035613,72.219117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,servicemix3,2968,2968,0,0.000000,0,0.000000,2968,0,0.000000,0,0,2968,0,0.000000,0.000000
50,servicemix4-bundles,7228,7227,3961,54.808358,1707,23.619759,7227,1707,23.619759,0,0,7227,1707,23.619759,23.616491
51,servicemix4-features,1085,1084,1,0.092251,0,0.000000,1084,0,0.000000,0,0,1084,0,0.000000,0.000000
52,servicemix4-kernel,526,525,0,0.000000,0,0.000000,525,0,0.000000,0,0,525,0,0.000000,0.000000
53,servicemix4-specs,254,254,159,62.598425,0,0.000000,254,0,0.000000,0,0,254,0,0.000000,0.000000
54,servicemix-components,225,225,55,24.444444,0,0.000000,225,0,0.000000,0,0,225,0,0.000000,0.000000
55,sirona,718,718,659,91.782730,661,92.061281,718,661,92.061281,0,0,718,661,92.061281,92.061281
56,struts-examples,68,67,65,97.014925,65,97.014925,67,65,97.014925,0,0,67,65,97.014925,95.588235
57,struts-sandbox,1875,353,175,49.575071,175,49.575071,353,175,49.575071,0,0,353,175,49.575071,9.333333
58,tajo,1212,1212,0,0.000000,0,0.000000,1212,0,0.000000,0,0,1212,0,0.000000,0.000000
59,tiles,1066,1023,639,62.463343,482,47.116325,1023,482,47.116325,34,0,1057,482,45.600757,45.215760
60,tiles-autotag,110,107,57,53.271028,18,16.822430,107,18,16.822430,0,0,107,18,16.822430,16.363636
61,tomee,8916,6955,0,0.000000,0,0.000000,8916,0,0.000000,0,0,8916,0,0.000000,0.000000
62,tuscany-sca-1.x,515,514,0,0.000000,0,0.000000,514,0,0.000000,0,0,514,0,0.000000,0.000000
63,tuscany-sca-2.x,4310,4309,0,0.000000,0,0.000000,4309,0,0.000000,0,0,4309,0,0.000000,0.000000
64,uima-addons,102,98,25,25.510204,0,0.000000,98,0,0.000000,0,0,98,0,0.000000,0.000000
65,uima-as,1409,389,0,0.000000,0,0.000000,389,0,0.000000,0,0,389,0,0.000000,0.000000
66,uima-ruta,1105,860,0,0.000000,0,0.000000,860,0,0.000000,0,0,860,0,0.000000,0.000000
67,uima-uimafit,236,235,171,72.765957,4,1.702128,235,4,1.702128,0,0,235,4,1.702128,1.694915
68,uima-uimaj,3863,867,0,0.000000,0,0.000000,867,0,0.000000,0,0,867,0,0.000000,0.000000
69,velocity-engine,3753,570,525,92.105263,525,92.105263,570,525,92.105263,0,0,570,525,92.105263,13.988809
70,velocity-tools,1207,460,296,64.347826,296,64.347826,460,296,64.347826,645,63,1168,359,30.736301,29.743165
71,vysper,678,671,555,82.712370,1,0.149031,671,1,0.149031,4,0,675,1,0.148148,0.147493
72,webservices-commons-xmlschema,373,336,318,94.642857,320,95.238095,336,320,95.238095,12,25,373,345,92.493298,92.493298
73,webservices-neethi,358,213,61,28.638498,55,25.821596,213,55,25.821596,9,2,224,57,25.446429,15.921788
74,whirr,568,564,74,13.120567,0,0.000000,564,0,0.000000,0,0,564,0,0.000000,0.000000
75,wicket,14818,7508,1407,18.740011,656,8.737347,7508,656,8.737347,0,0,7508,656,8.737347,4.427048
76,wink,892,891,0,0.000000,0,0.000000,891,0,0.000000,0,0,891,0,0.000000,0.000000
77,wookie,1921,151,0,0.000000,0,0.000000,151,0,0.000000,1396,0,1547,0,0.000000,0.000000
78,wss4j,1943,1080,460,33.724340,317,29.351852,1080,317,29.351852,306,548,1934,865,44.725957,44.518785

In [4]:
df.mean()

TotalCommits                    1764.417722
Original Buildable commits      1283.253165
Original                         287.810127
Original (%)                      37.197470
Replicated                       185.620253
Replicated (%)                    25.363013
Real Buildable commits          1366.582278
Real Replicated                  191.215190
Real Replicated (%)               25.423654
Ant Fails                         83.265823
Ant Success                       32.734177
Real Buildable commits + Ant    1482.582278
Real Replicated + Ant            223.949367
Real Replicated + Ant (%)         24.858411
Complete                          22.382664
dtype: float64

In [5]:
# Sum of each field
df.sum()

Project                         isisjames-hupajames-jdkimjames-jsievejames-jsp...
TotalCommits                                                               139389
Original Buildable commits                                                 101377
Original                                                                    22737
Original (%)                                                               2938.6
Replicated                                                                  14664
Replicated (%)                                                            2003.68
Real Buildable commits                                                     107960
Real Replicated                                                             15106
Real Replicated (%)                                                       2008.47
Ant Fails                                                                    6578
Ant Success                                                                  2586
Real Buildable commits + Ant                                               117124
Real Replicated + Ant                                                       17692
Real Replicated + Ant (%)                                                 1963.81
Complete                                                                  1768.23
dtype: object

In [6]:
df[['TotalCommits']].describe()

       TotalCommits
count     79.000000
mean    1764.417722
std     2694.935048
min       25.000000
25%      234.000000
50%      726.000000
75%     1898.000000
max    14818.000000

In [7]:
ant_success = int(df['Ant Success'].sum())
ant_fails   = int(df['Ant Fails'].sum())
print("Ant success: %d"%ant_success)
print("Ant fails: %d"%ant_fails)

Ant success: 2586
Ant fails: 6578

In [8]:
print("Buildable commits (Original) %d"%int(df['Original Buildable commits'].sum()))
print("Buildable commits (Our Study) %d"%int(df['Real Buildable commits'].sum()))
print("Buildable commits (Our Study + Ant) %d"%int(df['Real Buildable commits + Ant'].sum()))

Buildable commits (Original) 101377
Buildable commits (Our Study) 107960
Buildable commits (Our Study + Ant) 117124

Generate resume of Replication Experiment

In [9]:
report_df = df[['Project', 'TotalCommits','Original Buildable commits', 'Replicated']]
report_df.to_csv('replication_experiment_buildability_summary.csv', index=False)

In the next cell, we can see the projects where we detect commits that have building systems but they don't, getting different values in `Replicated` and `Real Replicated`

In [10]:
# Check projects with mistakes on original experiment
df[df['Replicated'] != df['Real Replicated']]

,Project,TotalCommits,Original Buildable commits,Original,Original (%),Replicated,Replicated (%),Real Buildable commits,Real Replicated,Real Replicated (%),Ant Fails,Ant Success,Real Buildable commits + Ant,Real Replicated + Ant,Real Replicated + Ant (%),Complete
7,jclouds,5074,1039,0,0.000000,0,0.000000,5072,94,1.853312,0,0,5072,94,1.853312,1.852582
26,maven-plugins,11812,11221,21,0.187149,21,0.187149,11810,369,3.124471,0,0,11810,369,3.124471,3.123942

In [11]:
# Projects in which we detect more buildable commits
diff_in_buildable_df = df[df['Original Buildable commits'] != df['Real Buildable commits']]
diff_in_buildable_df

,Project,TotalCommits,Original Buildable commits,Original,Original (%),Replicated,Replicated (%),Real Buildable commits,Real Replicated,Real Replicated (%),Ant Fails,Ant Success,Real Buildable commits + Ant,Real Replicated + Ant,Real Replicated + Ant (%),Complete
7,jclouds,5074,1039,0,0.000000,0,0.000000,5072,94,1.853312,0,0,5072,94,1.853312,1.852582
26,maven-plugins,11812,11221,21,0.187149,21,0.187149,11810,369,3.124471,0,0,11810,369,3.124471,3.123942
61,tomee,8916,6955,0,0.000000,0,0.000000,8916,0,0.000000,0,0,8916,0,0.000000,0.000000

In [12]:
# Diff between our buildable commits and their buildable commits
their_buildable_commits = int(diff_in_buildable_df[['Original Buildable commits']].sum())
our_buildable_commits   = int(diff_in_buildable_df[['Real Buildable commits']].sum())
our_buildable_commits-their_buildable_commits

6583

In [13]:
their_successfully_built_commits = int(diff_in_buildable_df[['Original']].sum())
our_successfully_built_commits   = int(diff_in_buildable_df[['Real Replicated']].sum())
our_successfully_built_commits-their_successfully_built_commits

442

Below, we can see an overview of the buildability of all projects. The values are percentages.

In [14]:
# Total
print("Successfully built commits (Original): %s"%df['Original'].sum())
print("Successfully built commits (Replicated): %s"%df['Replicated'].sum())
print("Buildable commits (Original): %s"%df['Original Buildable commits'].sum())
print("Total commits: %s"%df['TotalCommits'].sum())
df[['Original (%)','Replicated (%)']].describe()

Successfully built commits (Original): 22737
Successfully built commits (Replicated): 14664
Buildable commits (Original): 101377
Total commits: 139389

       Original (%)  Replicated (%)
count     79.000000       79.000000
mean      37.197470       25.363013
std       34.259306       33.277697
min        0.000000        0.000000
25%        2.908276        0.000000
50%       28.638498        8.737347
75%       65.997442       43.614583
max      100.000000      100.000000

We calculate the values of quartiles Q1 and Q3

In [15]:
q1 = df['TotalCommits'].quantile(0.25)
q1

234.0

In [16]:
q3 = df['TotalCommits'].quantile(0.75)
q3

1898.0

We get the buildability results for short projects (# of commits < Q1)

In [17]:
# Short proyects (< Q1)
short_df = df[ df['TotalCommits']< q1 ]
print("Successfully built commits (Original): %s"%short_df['Original'].sum())
print("Successfully built commits (Replicated): %s"%short_df['Replicated'].sum())
print("Buildable commits (Original): %s"%short_df['Original Buildable commits'].sum())
print("Total commits: %s"%short_df['TotalCommits'].sum())
short_df[['Original (%)','Replicated (%)']].describe()

Successfully built commits (Original): 1129
Successfully built commits (Replicated): 876
Buildable commits (Original): 2303
Total commits: 2349

       Original (%)  Replicated (%)
count     20.000000       20.000000
mean      49.846115       41.080037
std       35.084146       40.341705
min        0.000000        0.000000
25%       23.671875        0.555556
50%       48.635514       31.495912
75%       82.726359       80.622066
max       97.014925       99.118943

In [18]:
len(short_df)

20

We get the buildability results for medium projects (Q1 <= # of commits < Q3)

In [19]:
# Medium proyects (>= Q1 AND < Q3)
medium_df = df.query('TotalCommits >= %d and TotalCommits < %d'%(q1,q3))
print("Successfully built commits (Original): %s"%medium_df['Original'].sum())
print("Successfully built commits (Replicated): %s"%medium_df['Replicated'].sum())
print("Buildable commits (Original): %s"%medium_df['Original Buildable commits'].sum())
print("Total commits: %s"%medium_df['TotalCommits'].sum())
medium_df[['Original (%)','Replicated (%)']].describe()

Successfully built commits (Original): 9602
Successfully built commits (Replicated): 6049
Buildable commits (Original): 26761
Total commits: 33103

       Original (%)  Replicated (%)
count     39.000000       39.000000
mean      38.433182       21.146679
std       34.035972       29.631415
min        0.000000        0.000000
25%        4.994934        0.000000
50%       36.242083        1.702128
75%       68.426267       41.251547
max      100.000000       95.238095

We get the buildability results for large projects (# of commits >= Q3)

In [20]:
# Large proyects (>= Q1)
large_df = df[ df['TotalCommits'] >= q3 ]
print("Successfully built commits (Original): %s"%large_df['Original'].sum())
print("Successfully built commits (Replicated): %s"%large_df['Replicated'].sum())
print("Buildable commits (Original): %s"%large_df['Original Buildable commits'].sum())
print("Total commits: %s"%large_df['TotalCommits'].sum())
large_df[['Original (%)','Replicated (%)']].describe()

Successfully built commits (Original): 12006
Successfully built commits (Replicated): 7739
Buildable commits (Original): 72313
Total commits: 103937

       Original (%)  Replicated (%)
count     20.000000       20.000000
mean      22.139185       17.867842
std       29.331318       28.408516
min        0.000000        0.000000
25%        0.000000        0.000000
50%       16.485017        9.440663
75%       25.673890       19.171552
max      100.000000      100.000000

We used the Wilcoxon test to compare the buildability results obtained in the previous experiment with those obtained in the current experiment.

In [21]:
from scipy.stats import wilcoxon

original = list(df['Original (%)'])
replicated = list(df['Replicated (%)'])

wilcoxon(original,replicated)

WilcoxonResult(statistic=268.0, pvalue=1.9077637128196546e-06)

We get a very low p-value, so we can say that both results are different.